# Generated by Django 5.1.6 on 2025-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_redditpost_redditcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='post_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
