# Generated by Django 5.1.6 on 2025-02-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_redditpost_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='crypto_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
