# Generated by Django 5.1.6 on 2025-02-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_redditpost_crypto_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTokenSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_token', models.CharField(max_length=100)),
                ('overall_title_sentiment', models.FloatField()),
                ('overall_text_sentiment', models.FloatField()),
                ('overall_comment_sentiment', models.FloatField()),
                ('overall_sentiment', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTokenSpam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_token', models.CharField(max_length=100)),
                ('post_spam', models.FloatField()),
                ('comment_spam', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
