# Generated by Django 5.1.6 on 2025-02-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cryptotokensentiment_cryptotokenspam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotokensentiment',
            name='overall_comment_sentiment_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptotokensentiment',
            name='overall_sentiment_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptotokensentiment',
            name='overall_text_sentiment_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptotokensentiment',
            name='overall_title_sentiment_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptotokensentiment',
            name='overall_comment_sentiment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptotokensentiment',
            name='overall_sentiment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptotokensentiment',
            name='overall_text_sentiment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptotokensentiment',
            name='overall_title_sentiment',
            field=models.CharField(max_length=100),
        ),
    ]
